var ElecData=[
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-00-001",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09603",
     "Mains_Old_Reading": 4490,
     "Mains_New_Reading": 4919,
     "Consumed_Units": 429,
     "DG_Old_Reading": 43,
     "Dg_New_Reading": 48,
     "DG_Consumed_Units": 5
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-00-002",
     "Sanctioned_Load": 0,
     "Meter_No": "0",
     "Mains_Old_Reading": 13,
     "Mains_New_Reading": 13,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-00-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09605",
     "Mains_Old_Reading": 9096,
     "Mains_New_Reading": 9365,
     "Consumed_Units": 269,
     "DG_Old_Reading": 39,
     "Dg_New_Reading": 44,
     "DG_Consumed_Units": 5
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-00-004",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 101,
     "Mains_New_Reading": 101,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-01-001",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09482",
     "Mains_Old_Reading": 20017,
     "Mains_New_Reading": 20912,
     "Consumed_Units": 895,
     "DG_Old_Reading": 69,
     "Dg_New_Reading": 77,
     "DG_Consumed_Units": 8
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-01-002",
     "Sanctioned_Load": 0,
     "Meter_No": "0",
     "Mains_Old_Reading": 85,
     "Mains_New_Reading": 85,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-01-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09492",
     "Mains_Old_Reading": 47,
     "Mains_New_Reading": 47,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-01-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09483",
     "Mains_Old_Reading": 10093,
     "Mains_New_Reading": 10312,
     "Consumed_Units": 219,
     "DG_Old_Reading": 38,
     "Dg_New_Reading": 41,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-02-001",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09494",
     "Mains_Old_Reading": 4561,
     "Mains_New_Reading": 4588,
     "Consumed_Units": 27,
     "DG_Old_Reading": 7,
     "Dg_New_Reading": 7,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-02-002",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09496",
     "Mains_Old_Reading": 14177,
     "Mains_New_Reading": 14588,
     "Consumed_Units": 411,
     "DG_Old_Reading": 41,
     "Dg_New_Reading": 45,
     "DG_Consumed_Units": 4
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-02-003",
     "Sanctioned_Load": 0,
     "Meter_No": "0",
     "Mains_Old_Reading": 15,
     "Mains_New_Reading": 16,
     "Consumed_Units": 1,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-02-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09495",
     "Mains_Old_Reading": 6672,
     "Mains_New_Reading": 6954,
     "Consumed_Units": 282,
     "DG_Old_Reading": 22,
     "Dg_New_Reading": 25,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-03-001",
     "Sanctioned_Load": 0,
     "Meter_No": "0",
     "Mains_Old_Reading": 1,
     "Mains_New_Reading": 1,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-03-002",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09558",
     "Mains_Old_Reading": 5133,
     "Mains_New_Reading": 5491,
     "Consumed_Units": 358,
     "DG_Old_Reading": 46,
     "Dg_New_Reading": 50,
     "DG_Consumed_Units": 4
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-03-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09557",
     "Mains_Old_Reading": 11236,
     "Mains_New_Reading": 12034,
     "Consumed_Units": 798,
     "DG_Old_Reading": 51,
     "Dg_New_Reading": 62,
     "DG_Consumed_Units": 11
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-03-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09559",
     "Mains_Old_Reading": 2902,
     "Mains_New_Reading": 3020,
     "Consumed_Units": 118,
     "DG_Old_Reading": 9,
     "Dg_New_Reading": 9,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-04-001",
     "Sanctioned_Load": 8,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-04-002",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09593",
     "Mains_Old_Reading": 7523,
     "Mains_New_Reading": 7900,
     "Consumed_Units": 377,
     "DG_Old_Reading": 65,
     "Dg_New_Reading": 71,
     "DG_Consumed_Units": 6
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-04-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09595",
     "Mains_Old_Reading": 2097,
     "Mains_New_Reading": 2302,
     "Consumed_Units": 205,
     "DG_Old_Reading": 16,
     "Dg_New_Reading": 19,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-04-004",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 6359,
     "Mains_New_Reading": 7253,
     "Consumed_Units": 894,
     "DG_Old_Reading": 85,
     "Dg_New_Reading": 97,
     "DG_Consumed_Units": 12
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-05-001",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09501",
     "Mains_Old_Reading": 1833,
     "Mains_New_Reading": 2032,
     "Consumed_Units": 199,
     "DG_Old_Reading": 19,
     "Dg_New_Reading": 20,
     "DG_Consumed_Units": 1
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "Common Area",
     "Unit_No": "Borewell",
     "Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-05-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09500",
     "Mains_Old_Reading": 10363,
     "Mains_New_Reading": 11030,
     "Consumed_Units": 667,
     "DG_Old_Reading": 65,
     "Dg_New_Reading": 72,
     "DG_Consumed_Units": 7
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-05-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09569",
     "Mains_Old_Reading": 19235,
     "Mains_New_Reading": 19708,
     "Consumed_Units": 473,
     "DG_Old_Reading": 65,
     "Dg_New_Reading": 72,
     "DG_Consumed_Units": 7
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-06-001",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09591",
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-06-002",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09589",
     "Mains_Old_Reading": 10875,
     "Mains_New_Reading": 11146,
     "Consumed_Units": 271,
     "DG_Old_Reading": 40,
     "Dg_New_Reading": 44,
     "DG_Consumed_Units": 4
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-06-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09591",
     "Mains_Old_Reading": 194,
     "Mains_New_Reading": 194,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-06-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09594",
     "Mains_Old_Reading": 500,
     "Mains_New_Reading": 726,
     "Consumed_Units": 226,
     "DG_Old_Reading": 2,
     "Dg_New_Reading": 4,
     "DG_Consumed_Units": 2
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-07-001",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09570",
     "Mains_Old_Reading": 12995,
     "Mains_New_Reading": 13792,
     "Consumed_Units": 797,
     "DG_Old_Reading": 98,
     "Dg_New_Reading": 113,
     "DG_Consumed_Units": 15
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-07-002",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09571",
     "Mains_Old_Reading": 4213,
     "Mains_New_Reading": 4546,
     "Consumed_Units": 333,
     "DG_Old_Reading": 30,
     "Dg_New_Reading": 35,
     "DG_Consumed_Units": 5
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-07-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09568",
     "Mains_Old_Reading": 10639,
     "Mains_New_Reading": 10919,
     "Consumed_Units": 280,
     "DG_Old_Reading": 36,
     "Dg_New_Reading": 40,
     "DG_Consumed_Units": 4
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCA",
     "Unit_No": "CCA-07-004",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 44,
     "Mains_New_Reading": 44,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-00-001",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09738",
     "Mains_Old_Reading": 7124,
     "Mains_New_Reading": 7549,
     "Consumed_Units": 425,
     "DG_Old_Reading": 47,
     "Dg_New_Reading": 53,
     "DG_Consumed_Units": 6
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-00-002",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09615",
     "Mains_Old_Reading": 17368,
     "Mains_New_Reading": 17786,
     "Consumed_Units": 418,
     "DG_Old_Reading": 49,
     "Dg_New_Reading": 54,
     "DG_Consumed_Units": 5
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-00-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09752",
     "Mains_Old_Reading": 6710,
     "Mains_New_Reading": 6710,
     "Consumed_Units": 0,
     "DG_Old_Reading": 38,
     "Dg_New_Reading": 38,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-00-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09754",
     "Mains_Old_Reading": 281,
     "Mains_New_Reading": 281,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-01-001",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09525",
     "Mains_Old_Reading": 7104,
     "Mains_New_Reading": 7256,
     "Consumed_Units": 152,
     "DG_Old_Reading": 16,
     "Dg_New_Reading": 18,
     "DG_Consumed_Units": 2
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-01-002",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09506",
     "Mains_Old_Reading": 17862,
     "Mains_New_Reading": 18605,
     "Consumed_Units": 743,
     "DG_Old_Reading": 84,
     "Dg_New_Reading": 92,
     "DG_Consumed_Units": 8
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-01-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09526",
     "Mains_Old_Reading": 3,
     "Mains_New_Reading": 3,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-01-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09512",
     "Mains_Old_Reading": 7407,
     "Mains_New_Reading": 7872,
     "Consumed_Units": 465,
     "DG_Old_Reading": 33,
     "Dg_New_Reading": 35,
     "DG_Consumed_Units": 2
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-02-001",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 2936,
     "Mains_New_Reading": 3527,
     "Consumed_Units": 591,
     "DG_Old_Reading": 29,
     "Dg_New_Reading": 36,
     "DG_Consumed_Units": 7
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-02-002",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09549",
     "Mains_Old_Reading": 11187,
     "Mains_New_Reading": 11820,
     "Consumed_Units": 633,
     "DG_Old_Reading": 59,
     "Dg_New_Reading": 67,
     "DG_Consumed_Units": 8
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-02-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09576",
     "Mains_Old_Reading": 3457,
     "Mains_New_Reading": 3714,
     "Consumed_Units": 257,
     "DG_Old_Reading": 33,
     "Dg_New_Reading": 35,
     "DG_Consumed_Units": 2
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-02-004",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-03-001",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBW09524",
     "Mains_Old_Reading": 5460,
     "Mains_New_Reading": 5510,
     "Consumed_Units": 50,
     "DG_Old_Reading": 38,
     "Dg_New_Reading": 39,
     "DG_Consumed_Units": 1
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-03-002",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09552",
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-03-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09523",
     "Mains_Old_Reading": 10062,
     "Mains_New_Reading": 10609,
     "Consumed_Units": 547,
     "DG_Old_Reading": 71,
     "Dg_New_Reading": 76,
     "DG_Consumed_Units": 5
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-03-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09522",
     "Mains_Old_Reading": 18935,
     "Mains_New_Reading": 19344,
     "Consumed_Units": 409,
     "DG_Old_Reading": 81,
     "Dg_New_Reading": 85,
     "DG_Consumed_Units": 4
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-04-001",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-04-002",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-04-003",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 2920,
     "Mains_New_Reading": 3583,
     "Consumed_Units": 663,
     "DG_Old_Reading": 17,
     "Dg_New_Reading": 23,
     "DG_Consumed_Units": 6
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-04-004",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-05-001",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 337,
     "Mains_New_Reading": 502,
     "Consumed_Units": 165,
     "DG_Old_Reading": 3,
     "Dg_New_Reading": 6,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-05-002",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-05-003",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 1022,
     "Mains_New_Reading": 1415,
     "Consumed_Units": 393,
     "DG_Old_Reading": 7,
     "Dg_New_Reading": 12,
     "DG_Consumed_Units": 5
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-05-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09509",
     "Mains_Old_Reading": 10516,
     "Mains_New_Reading": 10810,
     "Consumed_Units": 294,
     "DG_Old_Reading": 39,
     "Dg_New_Reading": 42,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-06-001",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 70,
     "Mains_New_Reading": 70,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-06-002",
     "Sanctioned_Load": 8,
     "Mains_Old_Reading": 630,
     "Mains_New_Reading": 916,
     "Consumed_Units": 286,
     "DG_Old_Reading": 4,
     "Dg_New_Reading": 7,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-06-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09499",
     "Mains_Old_Reading": 11305,
     "Mains_New_Reading": 11636,
     "Consumed_Units": 331,
     "DG_Old_Reading": 71,
     "Dg_New_Reading": 77,
     "DG_Consumed_Units": 6
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-06-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09486",
     "Mains_Old_Reading": 11251,
     "Mains_New_Reading": 11251,
     "Consumed_Units": 0,
     "DG_Old_Reading": 45,
     "Dg_New_Reading": 45,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-07-001",
     "Sanctioned_Load": 8,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-07-002",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09573",
     "Mains_Old_Reading": 9240,
     "Mains_New_Reading": 9677,
     "Consumed_Units": 437,
     "DG_Old_Reading": 43,
     "Dg_New_Reading": 48,
     "DG_Consumed_Units": 5
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCB",
     "Unit_No": "CCB-07-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09572",
     "Mains_Old_Reading": 12334,
     "Mains_New_Reading": 12753,
     "Consumed_Units": 419,
     "DG_Old_Reading": 31,
     "Dg_New_Reading": 34,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-00-001",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09742",
     "Mains_Old_Reading": 19006,
     "Mains_New_Reading": 19469,
     "Consumed_Units": 463,
     "DG_Old_Reading": 43,
     "Dg_New_Reading": 47,
     "DG_Consumed_Units": 4
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-00-002",
     "Sanctioned_Load": 8,
     "Meter_No": "ASHI8791",
     "Mains_Old_Reading": 5191,
     "Mains_New_Reading": 5326,
     "Consumed_Units": 135,
     "DG_Old_Reading": 18,
     "Dg_New_Reading": 19,
     "DG_Consumed_Units": 1
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-00-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09619",
     "Mains_Old_Reading": 9637,
     "Mains_New_Reading": 9994,
     "Consumed_Units": 357,
     "DG_Old_Reading": 56,
     "Dg_New_Reading": 59,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-00-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09618",
     "Mains_Old_Reading": 15207,
     "Mains_New_Reading": 15534,
     "Consumed_Units": 327,
     "DG_Old_Reading": 34,
     "Dg_New_Reading": 38,
     "DG_Consumed_Units": 4
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-01-001",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09771",
     "Mains_Old_Reading": 35021,
     "Mains_New_Reading": 36299,
     "Consumed_Units": 1278,
     "DG_Old_Reading": 111,
     "Dg_New_Reading": 125,
     "DG_Consumed_Units": 14
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-01-002",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09769",
     "Mains_Old_Reading": 6453,
     "Mains_New_Reading": 6821,
     "Consumed_Units": 368,
     "DG_Old_Reading": 33,
     "Dg_New_Reading": 36,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-01-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09768",
     "Mains_Old_Reading": 9951,
     "Mains_New_Reading": 11025,
     "Consumed_Units": 1074,
     "DG_Old_Reading": 83,
     "Dg_New_Reading": 97,
     "DG_Consumed_Units": 14
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-01-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09531",
     "Mains_Old_Reading": 8594,
     "Mains_New_Reading": 9106,
     "Consumed_Units": 512,
     "DG_Old_Reading": 56,
     "Dg_New_Reading": 64,
     "DG_Consumed_Units": 8
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-02-001",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09663",
     "Mains_Old_Reading": 17616,
     "Mains_New_Reading": 18506,
     "Consumed_Units": 890,
     "DG_Old_Reading": 60,
     "Dg_New_Reading": 69,
     "DG_Consumed_Units": 9
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-02-002",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09770",
     "Mains_Old_Reading": 1698,
     "Mains_New_Reading": 1892,
     "Consumed_Units": 194,
     "DG_Old_Reading": 3,
     "Dg_New_Reading": 5,
     "DG_Consumed_Units": 2
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-02-003",
     "Sanctioned_Load": 8,
     "Mains_Old_Reading": 212,
     "Mains_New_Reading": 255,
     "Consumed_Units": 43,
     "DG_Old_Reading": 1,
     "Dg_New_Reading": 2,
     "DG_Consumed_Units": 1
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-02-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09698",
     "Mains_Old_Reading": 3996,
     "Mains_New_Reading": 4100,
     "Consumed_Units": 104,
     "DG_Old_Reading": 18,
     "Dg_New_Reading": 19,
     "DG_Consumed_Units": 1
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-03-001",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09528",
     "Mains_Old_Reading": 24701,
     "Mains_New_Reading": 24702,
     "Consumed_Units": 1,
     "DG_Old_Reading": 31,
     "Dg_New_Reading": 31,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-03-002",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09527",
     "Mains_Old_Reading": 25061,
     "Mains_New_Reading": 26007,
     "Consumed_Units": 946,
     "DG_Old_Reading": 126,
     "Dg_New_Reading": 137,
     "DG_Consumed_Units": 11
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-03-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09529",
     "Mains_Old_Reading": 22384,
     "Mains_New_Reading": 23275,
     "Consumed_Units": 891,
     "DG_Old_Reading": 72,
     "Dg_New_Reading": 81,
     "DG_Consumed_Units": 9
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-03-004",
     "Mains_Old_Reading": 2,
     "Mains_New_Reading": 2,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-04-001",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09481",
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-04-002",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09514",
     "Mains_Old_Reading": 5097,
     "Mains_New_Reading": 5503,
     "Consumed_Units": 406,
     "DG_Old_Reading": 27,
     "Dg_New_Reading": 30,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-04-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09479",
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-04-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09516",
     "Mains_Old_Reading": 2695,
     "Mains_New_Reading": 3464,
     "Consumed_Units": 769,
     "DG_Old_Reading": 11,
     "Dg_New_Reading": 23,
     "DG_Consumed_Units": 12
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-05-001",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 2333,
     "Mains_New_Reading": 2938,
     "Consumed_Units": 605,
     "DG_Old_Reading": 19,
     "Dg_New_Reading": 27,
     "DG_Consumed_Units": 8
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-05-002",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-05-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09515",
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-05-004",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 10,
     "Mains_New_Reading": 10,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-06-001",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09538",
     "Mains_Old_Reading": 2,
     "Mains_New_Reading": 2,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-06-002",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 14,
     "Mains_New_Reading": 14,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-06-003",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 7,
     "Mains_New_Reading": 7,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-06-004",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 833,
     "Mains_New_Reading": 1269,
     "Consumed_Units": 436,
     "DG_Old_Reading": 5,
     "Dg_New_Reading": 8,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-07-001",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09540",
     "Mains_Old_Reading": 4421,
     "Mains_New_Reading": 4624,
     "Consumed_Units": 203,
     "DG_Old_Reading": 33,
     "Dg_New_Reading": 36,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-07-002",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09505",
     "Mains_Old_Reading": 48022,
     "Mains_New_Reading": 49764,
     "Consumed_Units": 1742,
     "DG_Old_Reading": 156,
     "Dg_New_Reading": 177,
     "DG_Consumed_Units": 21
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-07-003",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCC",
     "Unit_No": "CCC-07-004",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-00-001",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09690",
     "Mains_Old_Reading": 5299,
     "Mains_New_Reading": 5489,
     "Consumed_Units": 190,
     "DG_Old_Reading": 23,
     "Dg_New_Reading": 26,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-00-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 1473,
     "Mains_New_Reading": 1501,
     "Consumed_Units": 28,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 1,
     "DG_Consumed_Units": 1
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-00-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09612",
     "Mains_Old_Reading": 43030,
     "Mains_New_Reading": 44684,
     "Consumed_Units": 1654,
     "DG_Old_Reading": 183,
     "Dg_New_Reading": 199,
     "DG_Consumed_Units": 16
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-00-004",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09613",
     "Mains_Old_Reading": 6951,
     "Mains_New_Reading": 7117,
     "Consumed_Units": 166,
     "DG_Old_Reading": 11,
     "Dg_New_Reading": 14,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-01-001",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09691",
     "Mains_Old_Reading": 4199,
     "Mains_New_Reading": 4576,
     "Consumed_Units": 377,
     "DG_Old_Reading": 24,
     "Dg_New_Reading": 28,
     "DG_Consumed_Units": 4
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-01-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 10,
     "Mains_New_Reading": 10,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-01-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09689",
     "Mains_Old_Reading": 1264,
     "Mains_New_Reading": 1303,
     "Consumed_Units": 39,
     "DG_Old_Reading": 3,
     "Dg_New_Reading": 3,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-01-004",
     "Sanctioned_Load": 8,
     "Meter_No": "WDE09779",
     "Mains_Old_Reading": 4259,
     "Mains_New_Reading": 4346,
     "Consumed_Units": 87,
     "DG_Old_Reading": 17,
     "Dg_New_Reading": 18,
     "DG_Consumed_Units": 1
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-02-001",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09732",
     "Mains_Old_Reading": 8487,
     "Mains_New_Reading": 8733,
     "Consumed_Units": 246,
     "DG_Old_Reading": 29,
     "Dg_New_Reading": 33,
     "DG_Consumed_Units": 4
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-02-002",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09733",
     "Mains_Old_Reading": 17,
     "Mains_New_Reading": 17,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-02-003",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 713,
     "Mains_New_Reading": 951,
     "Consumed_Units": 238,
     "DG_Old_Reading": 9,
     "Dg_New_Reading": 12,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-02-004",
     "Sanctioned_Load": 8,
     "Mains_Old_Reading": 307,
     "Mains_New_Reading": 445,
     "Consumed_Units": 138,
     "DG_Old_Reading": 2,
     "Dg_New_Reading": 3,
     "DG_Consumed_Units": 1
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-03-001",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09735",
     "Mains_Old_Reading": 756,
     "Mains_New_Reading": 756.01,
     "Consumed_Units": 0.009999999999990905,
     "DG_Old_Reading": 1,
     "Dg_New_Reading": 1,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-03-002",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09700",
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-03-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09697",
     "Mains_Old_Reading": 87,
     "Mains_New_Reading": 99,
     "Consumed_Units": 12,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 1,
     "DG_Consumed_Units": 1
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-03-004",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09701",
     "Mains_Old_Reading": 10554,
     "Mains_New_Reading": 10793,
     "Consumed_Units": 239,
     "DG_Old_Reading": 29,
     "Dg_New_Reading": 32,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-04-001",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09607",
     "Mains_Old_Reading": 10728,
     "Mains_New_Reading": 10734,
     "Consumed_Units": 6,
     "DG_Old_Reading": 63,
     "Dg_New_Reading": 64,
     "DG_Consumed_Units": 1
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-04-002",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09755",
     "Mains_Old_Reading": 9751,
     "Mains_New_Reading": 10350,
     "Consumed_Units": 599,
     "DG_Old_Reading": 58,
     "Dg_New_Reading": 67,
     "DG_Consumed_Units": 9
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-04-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09610",
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-04-004",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09756",
     "Mains_Old_Reading": 6496,
     "Mains_New_Reading": 6724,
     "Consumed_Units": 228,
     "DG_Old_Reading": 21,
     "Dg_New_Reading": 23,
     "DG_Consumed_Units": 2
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-05-001",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 14,
     "Mains_New_Reading": 29,
     "Consumed_Units": 15,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-05-002",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09762",
     "Mains_Old_Reading": 6890,
     "Mains_New_Reading": 7213,
     "Consumed_Units": 323,
     "DG_Old_Reading": 41,
     "Dg_New_Reading": 44,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-05-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09699",
     "Mains_Old_Reading": 4453,
     "Mains_New_Reading": 4987,
     "Consumed_Units": 534,
     "DG_Old_Reading": 32,
     "Dg_New_Reading": 38,
     "DG_Consumed_Units": 6
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-05-004",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09677",
     "Mains_Old_Reading": 4006,
     "Mains_New_Reading": 4141,
     "Consumed_Units": 135,
     "DG_Old_Reading": 15,
     "Dg_New_Reading": 18,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-06-001",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09554",
     "Mains_Old_Reading": 13344,
     "Mains_New_Reading": 13599,
     "Consumed_Units": 255,
     "DG_Old_Reading": 29,
     "Dg_New_Reading": 32,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-06-002",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09536",
     "Mains_Old_Reading": 3175,
     "Mains_New_Reading": 3200,
     "Consumed_Units": 25,
     "DG_Old_Reading": 9,
     "Dg_New_Reading": 10,
     "DG_Consumed_Units": 1
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-06-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09555",
     "Mains_Old_Reading": 6118,
     "Mains_New_Reading": 6589,
     "Consumed_Units": 471,
     "DG_Old_Reading": 45,
     "Dg_New_Reading": 51,
     "DG_Consumed_Units": 6
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-06-004",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09556",
     "Mains_Old_Reading": 8055,
     "Mains_New_Reading": 8378,
     "Consumed_Units": 323,
     "DG_Old_Reading": 38,
     "Dg_New_Reading": 42,
     "DG_Consumed_Units": 4
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-07-001",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09534",
     "Mains_Old_Reading": 12,
     "Mains_New_Reading": 15,
     "Consumed_Units": 3,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-07-002",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09535",
     "Mains_Old_Reading": 4521,
     "Mains_New_Reading": 4985,
     "Consumed_Units": 464,
     "DG_Old_Reading": 41,
     "Dg_New_Reading": 44,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-07-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09532",
     "Mains_Old_Reading": 2126,
     "Mains_New_Reading": 2563,
     "Consumed_Units": 437,
     "DG_Old_Reading": 2,
     "Dg_New_Reading": 10,
     "DG_Consumed_Units": 8
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "CCD",
     "Unit_No": "CCD-07-004",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09533",
     "Mains_Old_Reading": 14157,
     "Mains_New_Reading": 15185,
     "Consumed_Units": 1028,
     "DG_Old_Reading": 77,
     "Dg_New_Reading": 90,
     "DG_Consumed_Units": 13
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Unit_No": "COMMON AREA-1",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Unit_No": "COMMON AREA-Manager Office",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-00-001",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-00-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-00-003",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-00-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09751",
     "Mains_Old_Reading": 4858,
     "Mains_New_Reading": 5384,
     "Consumed_Units": 526,
     "DG_Old_Reading": 33,
     "Dg_New_Reading": 37,
     "DG_Consumed_Units": 4
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-01-001",
     "Sanctioned_Load": 8,
     "Mains_Old_Reading": 4602,
     "Mains_New_Reading": 5291,
     "Consumed_Units": 689,
     "DG_Old_Reading": 50,
     "Dg_New_Reading": 59,
     "DG_Consumed_Units": 9
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-01-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 1,
     "Mains_New_Reading": 1,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-01-003",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-01-004",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 2,
     "Mains_New_Reading": 2,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-02-001",
     "Sanctioned_Load": 8,
     "Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-02-002",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 3384,
     "Mains_New_Reading": 3876,
     "Consumed_Units": 492,
     "DG_Old_Reading": 34,
     "Dg_New_Reading": 41,
     "DG_Consumed_Units": 7
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-02-003",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_New_Reading": 187,
     "Consumed_Units": 187,
     "Dg_New_Reading": 9,
     "DG_Consumed_Units": 9
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-02-004",
     "Sanctioned_Load": 10.56,
     "Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-03-001",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09695",
     "Mains_Old_Reading": 3615,
     "Mains_New_Reading": 3814,
     "Consumed_Units": 199,
     "DG_Old_Reading": 42,
     "Dg_New_Reading": 46,
     "DG_Consumed_Units": 4
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-03-002",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09746",
     "Mains_Old_Reading": 22890,
     "Mains_New_Reading": 23632,
     "Consumed_Units": 742,
     "DG_Old_Reading": 149,
     "Dg_New_Reading": 152,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-03-003",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09620",
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-03-004",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-04-001",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09633",
     "Mains_Old_Reading": 8340,
     "Mains_New_Reading": 8831,
     "Consumed_Units": 491,
     "DG_Old_Reading": 59,
     "Dg_New_Reading": 59,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-04-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 222,
     "Mains_New_Reading": 675,
     "Consumed_Units": 453,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-04-003",
     "Sanctioned_Load": 8,
     "Meter_No": "WBE09634",
     "Mains_Old_Reading": 4420,
     "Mains_New_Reading": 4861,
     "Consumed_Units": 441,
     "DG_Old_Reading": 19,
     "Dg_New_Reading": 19,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-04-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09632",
     "Mains_Old_Reading": 1390,
     "Mains_New_Reading": 1390,
     "Consumed_Units": 0,
     "DG_Old_Reading": 4,
     "Dg_New_Reading": 4,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-05-001",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 608,
     "Mains_New_Reading": 809,
     "Consumed_Units": 201,
     "DG_Old_Reading": 3,
     "Dg_New_Reading": 3,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-05-002",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 32,
     "Mains_New_Reading": 32,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-05-003",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-05-004",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-06-001",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 1046,
     "Mains_New_Reading": 1556,
     "Consumed_Units": 510,
     "DG_Old_Reading": 9,
     "Dg_New_Reading": 9,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-06-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-06-003",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 1,
     "Mains_New_Reading": 48,
     "Consumed_Units": 47,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-06-004",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 25,
     "Mains_New_Reading": 26,
     "Consumed_Units": 1,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-07-001",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 1236,
     "Mains_New_Reading": 1796,
     "Consumed_Units": 560,
     "DG_Old_Reading": 13,
     "Dg_New_Reading": 13,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-07-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 1745,
     "Mains_New_Reading": 2357,
     "Consumed_Units": 612,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-07-003",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 53,
     "Mains_New_Reading": 53,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-07-004",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 12,
     "Mains_New_Reading": 12,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-08-001",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 6,
     "Mains_New_Reading": 6,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-08-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-08-003",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCA",
     "Unit_No": "FCA-08-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09649",
     "Mains_Old_Reading": 3578,
     "Mains_New_Reading": 4114,
     "Consumed_Units": 536,
     "DG_Old_Reading": 11,
     "Dg_New_Reading": 11,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-00-001",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09627",
     "Mains_Old_Reading": 11351,
     "Mains_New_Reading": 11748,
     "Consumed_Units": 397,
     "DG_Old_Reading": 45,
     "Dg_New_Reading": 49,
     "DG_Consumed_Units": 4
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-00-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-00-003",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 404,
     "Mains_New_Reading": 506,
     "Consumed_Units": 102,
     "DG_Old_Reading": 4,
     "Dg_New_Reading": 5,
     "DG_Consumed_Units": 1
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-00-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09678",
     "Mains_Old_Reading": 11174,
     "Mains_New_Reading": 11887,
     "Consumed_Units": 713,
     "DG_Old_Reading": 69,
     "Dg_New_Reading": 77,
     "DG_Consumed_Units": 8
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-01-001",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09579",
     "Mains_Old_Reading": 15245,
     "Mains_New_Reading": 16004,
     "Consumed_Units": 759,
     "DG_Old_Reading": 57,
     "Dg_New_Reading": 67,
     "DG_Consumed_Units": 10
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-01-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-01-003",
     "Sanctioned_Load": 10.56,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-01-004",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-02-001",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-02-002",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09519",
     "Mains_Old_Reading": 17866,
     "Mains_New_Reading": 18454,
     "Consumed_Units": 588,
     "DG_Old_Reading": 74,
     "Dg_New_Reading": 82,
     "DG_Consumed_Units": 8
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-02-003",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 3,
     "Consumed_Units": 3,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-02-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09521",
     "Mains_Old_Reading": 5947,
     "Mains_New_Reading": 6004,
     "Consumed_Units": 57,
     "DG_Old_Reading": 5,
     "Dg_New_Reading": 5,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-03-001",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-03-002",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09487",
     "Mains_Old_Reading": 8658,
     "Mains_New_Reading": 8690,
     "Consumed_Units": 32,
     "DG_Old_Reading": 9,
     "Dg_New_Reading": 9,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-03-003",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 12,
     "Mains_New_Reading": 47,
     "Consumed_Units": 35,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-03-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09581",
     "Mains_Old_Reading": 6689,
     "Mains_New_Reading": 7347,
     "Consumed_Units": 658,
     "DG_Old_Reading": 55,
     "Dg_New_Reading": 63,
     "DG_Consumed_Units": 8
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-04-001",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 21,
     "Mains_New_Reading": 31,
     "Consumed_Units": 10,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-04-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 11,
     "Mains_New_Reading": 14,
     "Consumed_Units": 3,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-04-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09640",
     "Mains_Old_Reading": 3870,
     "Mains_New_Reading": 4119,
     "Consumed_Units": 249,
     "DG_Old_Reading": 27,
     "Dg_New_Reading": 31,
     "DG_Consumed_Units": 4
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-04-004",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09638",
     "Mains_Old_Reading": 6139,
     "Mains_New_Reading": 6426,
     "Consumed_Units": 287,
     "DG_Old_Reading": 34,
     "Dg_New_Reading": 36,
     "DG_Consumed_Units": 2
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-05-001",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09766",
     "Mains_Old_Reading": 1939,
     "Mains_New_Reading": 2245,
     "Consumed_Units": 306,
     "DG_Old_Reading": 29,
     "Dg_New_Reading": 32,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-05-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 47,
     "Mains_New_Reading": 226,
     "Consumed_Units": 179,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 2,
     "DG_Consumed_Units": 2
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-05-003",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-05-004",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-06-001",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 31,
     "Mains_New_Reading": 507,
     "Consumed_Units": 476,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-06-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 3,
     "Mains_New_Reading": 3,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-06-003",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 51,
     "Mains_New_Reading": 51,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-06-004",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 1,
     "Mains_New_Reading": 2,
     "Consumed_Units": 1,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-07-001",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-07-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 60,
     "DG_Consumed_Units": 60
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-07-003",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-07-004",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-08-001",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 235,
     "Consumed_Units": 235,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-08-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 9,
     "Consumed_Units": 9,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-08-003",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCB",
     "Unit_No": "FCB-08-004",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-00-001",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-00-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-00-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09765",
     "Mains_Old_Reading": 8541,
     "Mains_New_Reading": 9186,
     "Consumed_Units": 645,
     "DG_Old_Reading": 23,
     "Dg_New_Reading": 23,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-00-004",
     "Sanctioned_Load": 8,
     "Mains_Old_Reading": 1854,
     "Mains_New_Reading": 2297,
     "Consumed_Units": 443,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-01-001",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-01-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-01-003",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 0,
     "Mains_New_Reading": 0,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-01-004",
     "Sanctioned_Load": 8,
     "Mains_Old_Reading": 647,
     "Mains_New_Reading": 1082,
     "Consumed_Units": 435,
     "DG_Old_Reading": 4,
     "Dg_New_Reading": 8,
     "DG_Consumed_Units": 4
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-02-001",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 4,
     "Mains_New_Reading": 10,
     "Consumed_Units": 6,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-02-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 598,
     "Mains_New_Reading": 709,
     "Consumed_Units": 111,
     "DG_Old_Reading": 3,
     "Dg_New_Reading": 4,
     "DG_Consumed_Units": 1
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-02-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09542",
     "Mains_Old_Reading": 5178,
     "Mains_New_Reading": 5454,
     "Consumed_Units": 276,
     "DG_Old_Reading": 43,
     "Dg_New_Reading": 46,
     "DG_Consumed_Units": 3
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-02-004",
     "Sanctioned_Load": 8,
     "Mains_Old_Reading": 406,
     "Mains_New_Reading": 406,
     "Consumed_Units": 0,
     "DG_Old_Reading": 5,
     "Dg_New_Reading": 5,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-03-001",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 23,
     "Mains_New_Reading": 133,
     "Consumed_Units": 110,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-03-002",
     "Sanctioned_Load": 0,
     "Meter_No": 0,
     "Mains_Old_Reading": 6,
     "Mains_New_Reading": 95,
     "Consumed_Units": 89,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 1,
     "DG_Consumed_Units": 1
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-03-003",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09487",
     "Mains_Old_Reading": 7430,
     "Mains_New_Reading": 7934,
     "Consumed_Units": 504,
     "DG_Old_Reading": 46,
     "Dg_New_Reading": 52,
     "DG_Consumed_Units": 6
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-03-004",
     "Sanctioned_Load": 8,
     "Mains_Old_Reading": 1,
     "Mains_New_Reading": 1,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-04-001",
     "Sanctioned_Load": 10.56,
     "Meter_No": "WBE09583",
     "Mains_Old_Reading": 25742,
     "Mains_New_Reading": 26381,
     "Consumed_Units": 639,
     "DG_Old_Reading": 102,
     "Dg_New_Reading": 109,
     "DG_Consumed_Units": 7
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-04-002",
     "Sanctioned_Load": 8,
     "Mains_Old_Reading": 4,
     "Mains_New_Reading": 4,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    },
    {
     "Month": "August-2022",
     "Project": "Rise",
     "Location": "FCC",
     "Unit_No": "FCC-04-003",
     "Sanctioned_Load": 10.56,
     "Mains_Old_Reading": 4,
     "Mains_New_Reading": 4,
     "Consumed_Units": 0,
     "DG_Old_Reading": 0,
     "Dg_New_Reading": 0,
     "DG_Consumed_Units": 0
    }
   ]

   export {ElecData}