const MOUTData=[
    {
     "gate_pass_id": "77a87542",
     "project": "One Rise HUB",
     "item_name": "FINISHING WORK/HOUSE KEEPING WORK/FLOOR DUSTER/",
     "quantity": 22,
     "unit": "kg",
     "out_date": "2022/06/15","time":"11:10 AM",
     "returnable": "No",
     "approx_returnable_time": "15/06/2022 10:53:34",
     "returned_quantity": 0,
     "balance_quantity": 22,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes"
    },
    {
     "gate_pass_id": "cbc32eec",
     "project": "One City Hamlet",
     "item_name": "FINISHING WORK/HOUSE KEEPING/DETERGENT POWDER/",
     "quantity": 1,
     "unit": "KG",
     "out_date": "2022/06/22","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "check": "Yes"
    },
    {
     "gate_pass_id": "7a2579c4",
     "project": "One City Hamlet",
     "item_name": "ELECTRICAL WORK/ELECTRIC FITTINGS &amp; ACCESSORIES/OLD MOTER STATER PANEL/",
     "quantity": 1,
     "unit": "Nos",
     "out_date": "2022/06/28","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "check": "Yes"
    },
    {
     "gate_pass_id": "06dbc4c2",
     "project": "One Rise HUB",
     "item_name": "TOOLS &amp; MACHINERY/MACHINERY/TILLU PUMP 1.0 HP/ANY BRAND",
     "quantity": 1,
     "unit": "Nos",
     "out_date": "2022/09/01","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "photo": "Material Out_Images/06dbc4c2.Photo.051910.jpg",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "Plumber Ranjeet le ke gaya"
    },
    {
     "gate_pass_id": "dcb9aac6",
     "project": "One City Hamlet",
     "item_name": "TOOLS &amp; MACHINERY/MACHINERY/TILLU PUMP 1.0 HP/ANY BRAND",
     "quantity": 1,
     "unit": "Nos",
     "out_date": "2022/09/04","time":"11:10 AM",
     "returnable": "Yes",
     "approx_returnable_time": "04/09/2022 17:43:55",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "photo": "Material Out_Images/dcb9aac6.Photo.061545.jpg",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "Ranjeet le ke geya"
    },
    {
     "gate_pass_id": "93b4a599",
     "project": "One City Hamlet",
     "item_name": "PLUMBING WORK/GI PIPE, FITTINGS &amp; ACCESSORIES/GI REDUCER SOCKET 25 X 20 MM/",
     "quantity": 2,
     "unit": "Nos",
     "out_date": "2022/09/04","time":"11:10 AM",
     "returnable": "Yes",
     "approx_returnable_time": "04/09/2022 18:04:00",
     "returned_quantity": 0,
     "balance_quantity": 2,
     "photo": "Material Out_Images/93b4a599.Photo.061310.jpg",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "Ranjeet le ke geya"
    },
    {
     "gate_pass_id": "c262e754",
     "project": "One City Mohali",
     "item_name": "PLUMBING WORK/GI PIPE, FITTINGS &amp; ACCESSORIES/GI NIPPLE 25 MM X 100 MM LONG/",
     "quantity": 2,
     "unit": "Nos",
     "out_date": "2022/09/04","time":"11:10 AM",
     "returnable": "Yes",
     "approx_returnable_time": "04/09/2022 17:48:00",
     "returned_quantity": 0,
     "balance_quantity": 2,
     "photo": "Material Out_Images/c262e754.Photo.061440.jpg",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "Ranjeet le ke geya plumber"
    },
    {
     "gate_pass_id": "96522b0e",
     "project": "One City Mohali",
     "item_name": "PLUMBING WORK/GI PIPE, FITTINGS &amp; ACCESSORIES/GI NIPPLE 20 MM X 75 MM LONG/ANY BRAND",
     "quantity": 2,
     "unit": "Nos",
     "out_date": "2022/09/04","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 2,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes"
    },
    {
     "gate_pass_id": "d2ddc3f3",
     "project": "One City Mohali",
     "item_name": "PLUMBING WORK/GI PIPE, FITTINGS &amp; ACCESSORIES/GI ELBOW 25 MM/",
     "quantity": 2,
     "unit": "Nos",
     "out_date": "2022/09/04","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 2,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes"
    },
    {
     "gate_pass_id": "ca80c917",
     "project": "One Rise HUB",
     "item_name": "PLUMBING WORK/Consumable/SECTION PIPE 50 MM/ANY BRAND",
     "quantity": 10.5,
     "unit": "mtr",
     "out_date": "2022/09/17","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 10.5,
     "photo": "Material Out_Images/ca80c917.Photo.142739.jpg",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "AMIT JE"
    },
    {
     "gate_pass_id": "1f2fd5a7",
     "project": "One Rise HUB",
     "item_name": "GENERAL HARDWARE/Consumable/PVC FOOTBALL 50 MM/ANY BRAND",
     "quantity": 1,
     "unit": "Nos",
     "out_date": "2022/09/17","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "photo": "Material Out_Images/1f2fd5a7.Photo.175652.png",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "amit je"
    },
    {
     "gate_pass_id": "62b19e97",
     "project": "One City Hamlet",
     "item_name": "ELECTRICAL WORK/ELECTRIC FITTINGS &amp; ACCESSORIES/SMPS 12V DC 400W 33.3 AMP/ANY BRAND",
     "quantity": 1,
     "unit": "Nos",
     "out_date": "2022/09/18","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "photo": "Material Out_Images/62b19e97.Photo.053025.jpg",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "KULDEEP VISHAWKARMA"
    },
    {
     "gate_pass_id": "46e27bcd",
     "project": "One City Hamlet",
     "item_name": "PLUMBING WORK/Consumable/PVC FOOTBALL 4 INCH/ANY BRAND",
     "quantity": 1,
     "unit": "Nos",
     "out_date": "2022/09/18","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "photo": "Material Out_Images/46e27bcd.Photo.024422.png",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "vikas bharti"
    },
    {
     "gate_pass_id": "788fcaeb",
     "project": "One City Hamlet",
     "item_name": "GENERAL HARDWARE/Consumable/PVC HOSE NIPPLE 4'/ANY BRAND",
     "quantity": 1,
     "unit": "Nos",
     "out_date": "2022/09/18","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "photo": "Material Out_Images/788fcaeb.Photo.024940.png",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "vikas bharti"
    },
    {
     "gate_pass_id": "991df1dc",
     "project": "One City Hamlet",
     "item_name": "GENERAL HARDWARE/Consumable/PATTI CLAMP 4\"/ANY BRAND",
     "quantity": 1,
     "unit": "Nos",
     "out_date": "2022/09/18","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "photo": "Material Out_Images/991df1dc.Photo.025552.png",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "vikas bharti"
    },
    {
     "gate_pass_id": "3413fb87",
     "project": "One City Hamlet",
     "item_name": "CONSTRUCTION SAFETY/SAFETY WORK/CAUTION TAPE/",
     "quantity": 3,
     "unit": "ROLL",
     "out_date": "2022/09/18","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 3,
     "photo": "Material Out_Images/3413fb87.Photo.030025.png",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "vikash bharti"
    },
    {
     "gate_pass_id": "090a36ae",
     "project": "One City Hamlet",
     "item_name": "BUILDING STRUCTURAL WORK/MS WIRE NAILS/MS WIRE NAILS 2''/",
     "quantity": 3,
     "unit": "KG",
     "out_date": "2022/09/28","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 3,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "KESHAW"
    },
    {
     "gate_pass_id": "030655fe",
     "project": "One City Hamlet",
     "item_name": "GENERAL HARDWARE/MS WIRE NAILS/MS WIRE NAILS 3''/",
     "quantity": 10,
     "unit": "KG",
     "out_date": "2022/09/28","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 10,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "KESHAW"
    },
    {
     "gate_pass_id": "e901908a",
     "project": "One City Hamlet",
     "item_name": "GENERAL HARDWARE/MS WIRE NAILS/MS WIRE NAILS 4''/",
     "quantity": 10,
     "unit": "KG",
     "out_date": "2022/09/28","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 10,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "KESHAW"
    },
    {
     "gate_pass_id": "4975d7cc",
     "project": "One City Hamlet",
     "item_name": "FINISHING WORK/TILES WORK/WHITE CEMENT/",
     "quantity": 1,
     "unit": "KG",
     "out_date": "2022/09/28","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "RAHUL PLUMBER"
    },
    {
     "gate_pass_id": "d9d68961",
     "project": "One City Hamlet",
     "item_name": "PLUMBING WORK/CHINAWARE/WC SEAT ENGLISH FLOOR STAND/",
     "quantity": 1,
     "unit": "NOS",
     "out_date": "2022/09/28","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "photo": "Material Out_Images/d9d68961.Photo.043920.jpg",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "RAHUL"
    },
    {
     "gate_pass_id": "48f660a1",
     "project": "One City Mohali",
     "item_name": "DIESEL",
     "quantity": 10,
     "unit": "LTR",
     "out_date": "2022/09/19",
     "returned_quantity": 0,
     "balance_quantity": 10,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "RAHUL (FOR DEWATERING) HAMLET 1"
    },
    {
     "gate_pass_id": "f681ab48",
     "project": "One City Mohali",
     "item_name": "DIESEL",
     "quantity": 10,
     "unit": "LTR",
     "out_date": "2022/09/19",
     "returned_quantity": 0,
     "balance_quantity": 10,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "PRAMOD OCH 1 DEWATERING PUMP"
    },
    {
     "gate_pass_id": "bc6e03cc",
     "project": "One City Mohali",
     "item_name": "SPANNER 21 - 23 NO",
     "quantity": 1,
     "unit": "NOS",
     "out_date": "2022/09/20","time":"11:10 AM",
     "returnable": "Yes",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "SANTOSH YADAV FOR WTP"
    },
    {
     "gate_pass_id": "2b578a64",
     "project": "One City Mohali",
     "item_name": "SIKANJA",
     "quantity": 10,
     "unit": "PCS",
     "out_date": "2022/09/20","time":"11:10 AM",
     "returnable": "Yes",
     "returned_quantity": 0,
     "balance_quantity": 10,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "SANTOSH YADAV"
    },
    {
     "gate_pass_id": "2e736a65",
     "project": "One City Mohali",
     "item_name": "GRINDER MACHINE 5\"",
     "quantity": 1,
     "unit": "NOS",
     "out_date": "2022/09/20","time":"11:10 AM",
     "returnable": "Yes",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "SANTOSH YADAV FOR OCH 1 WTP"
    },
    {
     "gate_pass_id": "3990d406",
     "project": "One City Mohali",
     "item_name": "KASSI",
     "quantity": 2,
     "unit": "NOS",
     "out_date": "2022/09/22","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 2,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "SANTI RAM"
    },
    {
     "gate_pass_id": "dc76f300",
     "project": "One City Mohali",
     "item_name": "DIESEL",
     "quantity": 10,
     "unit": "LTR",
     "out_date": "2022/09/23","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 10,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "RAHUL OCH 1"
    },
    {
     "gate_pass_id": "fec92bdd",
     "project": "One City Mohali",
     "item_name": "TOTAL STATION (TS02)",
     "quantity": 1,
     "unit": "SET",
     "out_date": "2022/09/24","time":"11:10 AM",
     "returnable": "Yes",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "JOGINDER JI"
    },
    {
     "gate_pass_id": "535ca6b0",
     "project": "One City Mohali",
     "item_name": "TOTAL STATION (TS02)",
     "quantity": 1,
     "unit": "NOS",
     "out_date": "2022/06/23","time":"11:10 AM",
     "returnable": "Yes",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "HEMRAJ (FOR REPAIRING )"
    },
    {
     "gate_pass_id": "f9bdd01e",
     "project": "One City Mohali",
     "item_name": "SHUTTERING JACK 2 X 3",
     "quantity": 50,
     "unit": "PCS",
     "out_date": "2022/06/24","time":"11:10 AM",
     "returnable": "Yes",
     "returned_quantity": 0,
     "balance_quantity": 50,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "AJAY (NAVEEN)"
    },
    {
     "gate_pass_id": "cc0332cc",
     "project": "One City Mohali",
     "item_name": "MS PIPE 100 MM",
     "quantity": 19,
     "unit": "LTH",
     "out_date": "2022/06/29","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 19,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "SANJEEV WELDER"
    },
    {
     "gate_pass_id": "8d665f25",
     "project": "One City Mohali",
     "item_name": "DIESEL",
     "quantity": 50,
     "unit": "LTR",
     "out_date": "2022/09/06",
     "returned_quantity": 0,
     "balance_quantity": 50,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "PRAMOD ELE (FOR OCH 1 DG)"
    },
    {
     "gate_pass_id": "0e6d1df6",
     "project": "One City Mohali",
     "item_name": "DIESEL",
     "quantity": 4,
     "unit": "LTR",
     "out_date": "2022/09/07",
     "returned_quantity": 0,
     "balance_quantity": 4,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "SANTI RAM (FOR GRASS CUTTING MACHINE)"
    },
    {
     "gate_pass_id": "56109e3d",
     "project": "One City Mohali",
     "item_name": "DIESEL",
     "quantity": 50,
     "unit": "LTR",
     "out_date": "2022/09/07",
     "returned_quantity": 0,
     "balance_quantity": 50,
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "DEVRAJ (FOR OCH 1 DG)"
    },
    {
     "gate_pass_id": "50d60920",
     "project": "One City Mohali",
     "item_name": "DIESEL",
     "quantity": 10,
     "unit": "LTR",
     "out_date": "2022/09/28",
     "returned_quantity": 0,
     "balance_quantity": 10,
     "check": "Yes",
     "comment": "GANESH OCH 2"
    },
    {
     "gate_pass_id": "d9b5bc91",
     "project": "One City Mohali",
     "item_name": "ELECTRICAL WORK/CABLE/ALUMINIUM CABLE 25 SQMM X 3.5 CORE/",
     "quantity": 90,
     "unit": "Meter",
     "out_date": "2022/09/29","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 90,
     "photo": "Material Out_Images/d9b5bc91.Photo.101047.jpg",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "PRAMOD ELE FOR BINDING MACHINE CONNECTION OCH 1"
    },
    {
     "gate_pass_id": "96e204aa",
     "project": "One City Mohali",
     "item_name": "ELECTRICAL WORK/ELECTRIC MCB, RCCB ASSY/MCB 63 AMP TPN/ATHENA",
     "quantity": 1,
     "unit": "Nos",
     "out_date": "2022/09/29","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "photo": "Material Out_Images/96e204aa.Photo.115725.jpg",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "PRAMOD ELE OCH 1 LABOUR CAMP"
    },
    {
     "gate_pass_id": "94c1ac4a",
     "project": "One City Mohali",
     "item_name": "ELECTRICAL WORK/ELECTRIC MCB, RCCB ASSY/ELCB 63AMP -2M-100MA/ATHENA",
     "quantity": 1,
     "unit": "Nos",
     "out_date": "2022/09/29","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "photo": "Material Out_Images/94c1ac4a.Photo.115626.jpg",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "PRAMOD ELE OCH 1 LABOUR CAMP"
    },
    {
     "gate_pass_id": "b842fa33",
     "project": "One City Mohali",
     "item_name": "GENERAL HARDWARE/Consumable/SUCTION PIPE 4\" (HEAVY)/ANY BRAND",
     "quantity": 25,
     "unit": "MTR",
     "out_date": "2022/09/30","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 25,
     "photo": "Material Out_Images/b842fa33.Photo.050152.jpg",
     "gaurd_name": "Sukhwinder Singh",
     "check": "Yes",
     "comment": "pramod ele c block"
    },
    {
     "gate_pass_id": "6517a632",
     "project": "One City Mohali",
     "item_name": "PLUMBING WORK/Consumable/PVC FOOTVALVE  4 INCH/ANY BRAND",
     "quantity": 1,
     "unit": "Nos",
     "out_date": "2022/09/30","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "check": "Yes",
     "comment": "c block"
    },
    {
     "gate_pass_id": "2369e34e",
     "project": "One City Mohali",
     "item_name": "GENERAL HARDWARE/Consumable/PATTI CLAMP 50MM/ANY BRAND",
     "quantity": 1,
     "unit": "Nos",
     "out_date": "2022/09/30","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "check": "Yes",
     "comment": "pramod ele c block"
    },
    {
     "gate_pass_id": "1180a0e9",
     "project": "One City Hamlet",
     "item_name": "ELECTRICAL WORK/LED LIGHTS/LED STREET LIGHT 70 WATT/ANY BRAND",
     "quantity": 6,
     "unit": "Nos",
     "out_date": "2022/09/03","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 6,
     "check": "Yes",
     "comment": "pramod ele"
    },
    {
     "gate_pass_id": "73ebc43b",
     "project": "One City Hamlet",
     "item_name": "ELECTRICAL WORK/CABLE/COPPER CABLE 2.5 SQMM X 3 CORE/",
     "quantity": 20,
     "unit": "Meter",
     "out_date": "2022/09/03","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 20,
     "photo": "Material Out_Images/73ebc43b.Photo.045826.jpg",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "pramod ele le ke ja rha"
    },
    {
     "gate_pass_id": "0447551f",
     "project": "One City Hamlet",
     "item_name": "TOOLS &amp; MACHINERY/MACHINERY/TILLU PUMP 1.0 HP/ANY BRAND",
     "quantity": 1,
     "unit": "Nos",
     "out_date": "2022/09/03","time":"11:10 AM",
     "returnable": "Yes",
     "approx_returnable_time": "04/09/2022 23:15:25",
     "returned_quantity": 0,
     "balance_quantity": 1,
     "photo": "Material Out_Images/0447551f.Photo.052204.jpg",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "PRAMOD ELE le k geya"
    },
    {
     "gate_pass_id": "1582d7f2",
     "project": "One City Hamlet",
     "item_name": "CONSTRUCTION CHEMICALS AND OILS/HOUSE KEEPING WORK/ACID(HCL)/",
     "quantity": 5,
     "unit": "LTR",
     "out_date": "2022/09/04","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 5,
     "check": "Yes",
     "comment": "PRAMOD ELE OCH 1"
    },
    {
     "gate_pass_id": "3e42038e",
     "project": "One City Hamlet",
     "item_name": "FINISHING WORK/CONSUMABLE/OLD CLOTHS/",
     "quantity": 3,
     "unit": "Nos",
     "out_date": "2022/09/04","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 3,
     "photo": "Material Out_Images/3e42038e.Photo.040035.jpg",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "PRAMOD ELE OCH 1"
    },
    {
     "gate_pass_id": "5d436f64",
     "project": "One City Hamlet",
     "item_name": "BUILDING STRUCTURAL WORK/MS SCAFFOLDING MATERIAL/MS PROPS/JACK 2 X 3 MTR/",
     "quantity": 50,
     "unit": "Nos",
     "out_date": "2022/09/05","time":"11:10 AM",
     "returnable": "Yes",
     "approx_returnable_time": "31/09/2022 17:00:21",
     "returned_quantity": 0,
     "balance_quantity": 50,
     "photo": "Material Out_Images/5d436f64.Photo.092036.jpg",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "FAGU LAL FOR WTP"
    },
    {
     "gate_pass_id": "0fd7ee0e",
     "project": "One City Mohali",
     "item_name": "Standard",
     "quantity": 28,
     "unit": "Nos",
     "out_date": "2022/09/05","time":"11:10 AM",
     "returnable": "Yes",
     "approx_returnable_time": "31/09/2022 12:56:00",
     "returned_quantity": 0,
     "balance_quantity": 28,
     "photo": "Material Out_Images/0fd7ee0e.Photo.091923.jpg",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "Fagu lal for wtp"
    },
    {
     "gate_pass_id": "f1470e3e",
     "project": "One City Mohali",
     "item_name": "Ledger",
     "quantity": 60,
     "unit": "Nos",
     "out_date": "2022/09/05","time":"11:10 AM",
     "returnable": "Yes",
     "approx_returnable_time": "31/09/2022 12:57:00",
     "returned_quantity": 0,
     "balance_quantity": 60,
     "photo": "Material Out_Images/f1470e3e.Photo.091826.jpg",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "Fagu lal for wtp"
    },
    {
     "gate_pass_id": "efafb48a",
     "project": "One City Hamlet",
     "item_name": "BUILDING STRUCTURAL WORK/MS WIRE NAILS/MS WIRE NAILS 2''/",
     "quantity": 3.2,
     "unit": "KG",
     "out_date": "2022/09/05","time":"11:10 AM",
     "returnable": "No",
     "returned_quantity": 0,
     "balance_quantity": 3.2,
     "photo": "Material Out_Images/efafb48a.Photo.101409.jpg",
     "gaurd_name": "Gurpreet Singh",
     "check": "Yes",
     "comment": "KESHAW FOR WTP"
    }
   ]


   export {MOUTData}